module.exports = {
  apps: [
    {
      name: "orchestrator",
      interpreter: "./venv/bin/python",
      script: "orchestrator.py",
      cwd: __dirname,
      error_file: "./logs/orchestrator-error.log",
      out_file: "./logs/orchestrator-out.log",
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
    {
      name: "accumulation-monitor",
      interpreter: "./venv/bin/python",
      script: "accumulation_monitor.py",
      cwd: __dirname,
      error_file: "./logs/accumulation-error.log",
      out_file: "./logs/accumulation-out.log",
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
    // {
    //   name: "telegram-bot",
    //   interpreter: "./venv/bin/python",
    //   script: "telegram_bot.py",
    //   cwd: __dirname,
    //   error_file: "./logs/telegram_bot-error.log",
    //   out_file: "./logs/telegram_bot-out.log",
    //   merge_logs: true,
    //   autorestart: true,
    //   max_restarts: 10,
    //   restart_delay: 5000,
    // },
  ],
};
